name: docker

on:
    push:
        branches: ["main"]
        tags: ["v*", "RELEASE.*"] # 按需保留你的标签模式
    pull_request:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Ensure Docker Hub secrets
              run: |
                  if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
                    echo "Missing DOCKERHUB_USERNAME or DOCKERHUB_TOKEN secrets"; exit 1;
                  fi

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # ✅ 这里把镜像名转成小写
            - name: Set image name (lowercase)
              id: img
              shell: bash
              run: |
                  echo "image=$(echo '${{ secrets.DOCKERHUB_USERNAME }}/minio' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ steps.img.outputs.image }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=tag
                      type=sha
                      type=raw,value=latest,enable={{is_default_branch}}

            # 计算 VERSION/COMMIT（与你的 Dockerfile -ldflags 对应）
            - name: Compute build args
              id: vars
              shell: bash
              run: |
                  if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
                    echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
                  else
                    echo "VERSION=dev-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
                  fi
                  echo "COMMIT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

            - name: Build and push (multi-arch)
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile.source
                  platforms: linux/amd64,linux/arm64
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      VERSION=${{ steps.vars.outputs.VERSION }}
                      COMMIT=${{ steps.vars.outputs.COMMIT }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  provenance: true
                  sbom: true
